spring:
  profiles:
    active: dev
  redis:
    host: ${SOOLSOOL_REDIS_HOST}
    port: ${SOOLSOOL_REDIS_PORT}

management:
  endpoints:
    web:
      exposure:
        include: prometheus, health

security:
  jwt:
    token:
      secret-key: ${SOOLSOOL_JWT_SECRET}
      expire-length: 3600000

kakao:
  admin:
    key: ${SOOLSOOL_KAKAO_ADMIN_KEY}

logging:
  slack:
    webhook-url: ${SOOLSOOL_LOGGING_SLACK_WEBHOOK_URL}
server:
  servlet:
    context-path: /api
