spring:
  profiles:
    active: dev-h2

management:
  endpoints:
    web:
      exposure:
        include: prometheus

security:
  jwt:
    token:
      secret-key: ${SOOLSOOL_JWT_SECRET}
      expire-length: 3600000

kakao:
  admin:
    key: ${SOOLSOOL_KAKAO_ADMIN_KEY}

logging:
  slack:
    webhook-url: ${SOOLSOOL_LOGGING_SLACK_WEBHOOK_URL}
