spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SOOLSOOL_MYSQL_URL}
    username: ${SOOLSOOL_MYSQL_USERNAME}
    password: ${SOOLSOOL_MYSQL_PASSWORD}
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    defer-datasource-initialization: true
