name: Check code status

on: push

jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: shogo82148/actions-setup-redis@v1
        with:
          redis-version: '6.x'

      - name: Set environment variables to runner
        run: |
          echo SOOLSOOL_JWT_SECRET=${{ secrets.SOOLSOOL_JWT_SECRET }} >> $GITHUB_ENV

      - name: Set environment variables to runner
        run: |
          echo SOOLSOOL_KAKAO_ADMIN_KEY=${{ secrets.SOOLSOOL_KAKAO_ADMIN_KEY }} >> $GITHUB_ENV

      - name: Set environment variables to runner
        run: |
          echo SOOLSOOL_REDIS_HOST=localhost >> $GITHUB_ENV

      - name: Set environment variables to runner
        run: |
          echo SOOLSOOL_REDIS_PORT=${{ secrets.SOOLSOOL_REDIS_PORT }} >> $GITHUB_ENV

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'corretto'

      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Test, Build with Gradle and analyze with Sonar cloud
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew test build sonar --info
