name: Labeler for issue and pull request

on:
  issues:
    types: [ opened, edited, milestoned ]
  pull_request_target:
    types: [ opened ]

jobs:
  labeler:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: write
    steps:
      - name: Sync label
        id: labeler
        uses: jimschubert/labeler-action@v2
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
